FROM ubuntu:18.04
# MAINTAINER Stephen G. Odaibo, MD
COPY . /app
WORKDIR /app
# RUN pwd
# RUN apt install python3.8
# RUN pip install --no-cache-dir -r requirement1.txt
# ENTRYPOINT ["python", "hdf5_to_pb.py"]
# FROM httpd:2.4
# COPY ./ /usr/local/apache2/htdocs/
